//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appWEB.ServiceReferenceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWCF.IServiceWCF")]
    public interface IServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/ListarEmpleado", ReplyAction="http://tempuri.org/IServiceWCF/ListarEmpleadoResponse")]
        System.Data.DataSet ListarEmpleado(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/DevuelveDatosEmpleado", ReplyAction="http://tempuri.org/IServiceWCF/DevuelveDatosEmpleadoResponse")]
        string DevuelveDatosEmpleado(int codUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/CargarConversacion", ReplyAction="http://tempuri.org/IServiceWCF/CargarConversacionResponse")]
        System.Data.DataSet CargarConversacion(int codUsuarioEnvia, int codUsuarioRecibe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/RegistrarConversacion", ReplyAction="http://tempuri.org/IServiceWCF/RegistrarConversacionResponse")]
        bool RegistrarConversacion(string conversacion, int codUsuEnvia, int codUsuRecibe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/DevuelveCodUsuUltimoMensaje", ReplyAction="http://tempuri.org/IServiceWCF/DevuelveCodUsuUltimoMensajeResponse")]
        int DevuelveCodUsuUltimoMensaje(int codUsuEnvia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/DevuelveFechaHoraUltiMensaje", ReplyAction="http://tempuri.org/IServiceWCF/DevuelveFechaHoraUltiMensajeResponse")]
        string DevuelveFechaHoraUltiMensaje(int codUsuEnvia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceWCFChannel : appWEB.ServiceReferenceWCF.IServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWCFClient : System.ServiceModel.ClientBase<appWEB.ServiceReferenceWCF.IServiceWCF>, appWEB.ServiceReferenceWCF.IServiceWCF {
        
        public ServiceWCFClient() {
        }
        
        public ServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarEmpleado(int codUsuario) {
            return base.Channel.ListarEmpleado(codUsuario);
        }
        
        public string DevuelveDatosEmpleado(int codUsuario) {
            return base.Channel.DevuelveDatosEmpleado(codUsuario);
        }
        
        public System.Data.DataSet CargarConversacion(int codUsuarioEnvia, int codUsuarioRecibe) {
            return base.Channel.CargarConversacion(codUsuarioEnvia, codUsuarioRecibe);
        }
        
        public bool RegistrarConversacion(string conversacion, int codUsuEnvia, int codUsuRecibe) {
            return base.Channel.RegistrarConversacion(conversacion, codUsuEnvia, codUsuRecibe);
        }
        
        public int DevuelveCodUsuUltimoMensaje(int codUsuEnvia) {
            return base.Channel.DevuelveCodUsuUltimoMensaje(codUsuEnvia);
        }
        
        public string DevuelveFechaHoraUltiMensaje(int codUsuEnvia) {
            return base.Channel.DevuelveFechaHoraUltiMensaje(codUsuEnvia);
        }
    }
}
